<?php

/**
 * @file
 * RSVPList module hooks.
 */

use Drupal\Core\Form\FormStateInterface;


/**
 * Implements hook_form_alter().
 */
function rsvplist_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  \Drupal::messenger()->addMessage(t('form_id of this form is @id', ['@id' => $form_id]));
  //dpm("hello from rsvplist_form_alter");
  //\Drupal::messenger()->addMessage("hello from rsvplist_form_alter");
  //dpm($form_state);
}
