<?php

/**
 * @file
 * Contains the settings for administrating the RSVP Form
 */

namespace Drupal\rsvplist\Form;

use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;


class RSVPSettingsForm extends ConfigFormBase {

  protected function getEditableConfigNames() {
    return ['rsvplist.settings'];
  }

  public function getFormId() {
    return 'rsvplist_admin_settings';
  }

  public function buildForm(array $form, FormStateInterface $form_state) {
    $types = node_type_get_names();
    $config = $this->config('rsvplist.settings');
    $form['rsvplist_types'] = [
      '#type' => 'checkboxes',
      '#title' => $this->t('The content types to enable RSVP collection for'),
      '#default_value' => $config->get('allowed_types'),
      '#options' => $types,
      '#description' => $this->t('On the specified node types, an RSVP option will be available and can be
                                  enabled while the node is being edited.'),
    ];
    $form['array_filter'] = ['#type' => 'value', '#value' => TRUE];

    return parent::buildForm($form, $form_state); // TODO: Change the autogenerated stub
  }

  public function submitForm(array &$form, FormStateInterface $form_state) {
    $allowed_types = array_filter($form_state->getValue('rsvplist_types'));
    sort($allowed_types);

    $this->config('rsvplist.settings')
           ->set('allowed_types', $allowed_types);

    parent::submitForm($form, $form_state); // TODO: Change the autogenerated stub
  }
}
